### ISSUE TITLE
test failure in nullspace()

### ISSUE THREAD

**Issue by mezzarobba** [mkauers/ore_algebra#49]
```
sage -t --random-seed=27781961452623769453936609103941074692 src/ore_algebra/nullspace.py
**********************************************************************
File "src/ore_algebra/nullspace.py", line 2000, in ore_algebra.nullspace.clear.compress_solver
Failed example:
    A*V[0]
Exception raised:
    Traceback (most recent call last):
      File "/home/marc/co/sage/src/sage/doctest/forker.py", line 695, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/marc/co/sage/src/sage/doctest/forker.py", line 1093, in compile_and_execute
        exec(compiled, globs)
      File "<doctest ore_algebra.nullspace.clear.compress_solver[4]>", line 1, in <module>
        A*V[Integer(0)]
    IndexError: list index out of range
**********************************************************************
```

**Comment by mkauers** [comment]
Unable to reproduce this. Can you post the matrix A that is chosen when you run this test?

**Comment by mezzarobba** [comment]
```
R.<x> = ZZ[]
A = matrix(R, [[1, 0, -x^2 - x + 10, 10*x + 11, x^2 - x - 1], [0, -2, 1, 
0, 0], [0, 0, 2, 0, 11*x^2 - x + 6], [0, 0, 0, 0, x^2 + x + 32]])
```
The random choices made by `wiedemann()` when running the test are:
```
x_base = (0, -1, -7*x^2 + 2*x, 0, x + 7)
y = (0, 36, 0, -2*x + 1, -x^2 - 3*x)
```
With other random choices, it works.

**Comment by mkauers** [comment]
Thanks, I'll have a look.
