### ISSUE TITLE
IndentationError

### ISSUE THREAD

**Issue by Antoine-Poincare** [mkauers/ore_algebra#68]
```diff
--- a/src/ore_algebra/differential_operator_1_1.py
+++ b/src/ore_algebra/differential_operator_1_1.py
@@ -1730,7 +1730,7 @@ class UnivariateDifferentialOperatorOverUnivariateRing(UnivariateOreOperatorOver
                     print("Value function", vect)
                 return min(vect)
 
-              def raise_val_fct(ops, place, dim=None, base=C, iota=None,
+            def raise_val_fct(ops, place, dim=None, base=C, iota=None,
                               infolevel=0, **kwargs):
                 # TODO: Is it okay that we don't use dim?
                 ops = [ore_ext([c(x=x+xi)
```

**Comment by videlec** [comment]
Indeed, installing at commit [7014c6f](https://github.com/mkauers/ore_algebra/commit/7014c6f1dc00245948e51e4fbc7094280ebe5ae5) we get
```
sage: import ore_algebra
Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-010f137b6fc1>", line 4, in <module>
    Ax = OreAlgebra(QQx, 'Dx')

  File "/home/doctorant/.sage/local/lib/python3.10/site-packages/ore_algebra/ore_algebra.py", line 962, in OreAlgebra
    from . import (

  File "/home/doctorant/.sage/local/lib/python3.10/site-packages/ore_algebra/differential_operator_1_1.py", line 1733
    def raise_val_fct(ops, place, dim=None, base=C, iota=None,
                                                              ^
IndentationError: unindent does not match any outer indentation level
```

**Comment by mkauers** [comment]
Fixed. Thanks.
